version: '3.1'
services:

  main-server:
    container_name: main-server-container
    build: explore-with-me-main/explore-with-me-main-server
    depends_on:
      - main-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: kitty
      POSTGRES_PASSWORD: kitty
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/explore-with-me-main
      STATS_SERVER_URL: http://stats-server:9090

  main-db:
    container_name: main-db-container
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: explore-with-me-main
      POSTGRES_USER: kitty
      POSTGRES_PASSWORD: kitty

  stats-server:
    container_name: stats-server-container
    build: explore-with-me-stats/explore-with-me-stats-service
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      POSTGRES_USER: kitty
      POSTGRES_PASSWORD: kitty
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/explore-with-me-stats

  stats-db:
    container_name: stats-db-container
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: explore-with-me-stats
      POSTGRES_USER: kitty
      POSTGRES_PASSWORD: kitty
