version: '3.1'
services:

  stats-server:
    build: explore-with-me-stats/explore-with-me-stats-service
    depends_on:
    - stats-db
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
