version: '3.1'
services:

  stats-server:
    container_name: stats-server-container
    build: explore-with-me-stats/explore-with-me-stats-service
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      POSTGRES_USER: kitty
      POSTGRES_PASSWORD: kitty
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/explore-with-me-stats

  stats-db:
    container_name: stats-db-container
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: explore-with-me-stats
      POSTGRES_USER: kitty
      POSTGRES_PASSWORD: kitty
