spring:
  mvc:
    format:
      date: "yyyy-MM-dd"
      time: "HH:mm:ss"
      date-time: "yyyy-MM-dd HH:mm:ss"

server:
  port: 9090

---

spring:
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile:
        - default
        - prod

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

    generate-ddl: false
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

---

spring:
  config:
    activate:
      on-profile:
        - ci
        - test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm-stats
    username: test
    password: test

logging:
  level:
    web: debug
