spring:
  sql:
    init:
      mode: always
  datasource:
    username: kitty
    password: kitty
    url: jdbc:postgresql://localhost:5432/explore-with-me-main
    driver-class-name: org.postgresql.Driver
